# For more details, see https://docs.github.com/en/actions
name: Build sunny-tis images

# Controls when the workflow will run
on: workflow_dispatch

defaults:
  run:
    shell: bash

# For more details, see https://github.com/docker/build-push-action
jobs:
  runtime:
    name: Runtime
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: runtime
          platforms: linux/amd64,linux/arm64
          push: true
          tags: qubo188612/sunny-tis:runtime
          cache-from: type=registry,ref=qubo188612/sunny-tis:runtime
          cache-to: type=inline
  dev:
    name: Development
    runs-on: ubuntu-20.04
    needs: [runtime]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: qubo188612/sunny-tis:dev
          cache-from: type=registry,ref=qubo188612/sunny-tis:dev
          cache-to: type=inline
  deploy:
    name: Deployment
    runs-on: ubuntu-20.04
    needs: [dev]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: deploy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: qubo188612/sunny-tis:deploy2064
          cache-from: type=registry,ref=qubo188612/sunny-tis:deploy2064
          cache-to: type=inline
  desktop:
    name: Desktop
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: desktop
          platforms: linux/amd64
          push: true
          tags: qubo188612/sunny-tis:desktop
          cache-from: type=registry,ref=qubo188612/sunny-tis:desktop
          cache-to: type=inline
